### ISSUE TITLE
sled doesn't clean blobs

### ISSUE THREAD

**Issue by StaffEngineer** [johanhelsing/bevy_pkv#27]
Just sharing the findings... feel free to close the issue. 

I was inserting/removing data from pkv using sled backend but data folder always was growing in size, even when pkv.clear is called. I switched to rocksdb backend and now the size of data directory is adequate: it growth with new data added, and shrinks with removing data from db, with sled backend it is always growing.

Environment: Mac M1

**Comment by johanhelsing** [comment]
interesting. If you add 10 000 items, then clear, then add 10 000 other items, is it twice as big as after the first 10 000 items, or the same size?

**Comment by StaffEngineer** [comment]
I am adding items through UI, so 10000 items is too big amount for quick testing for me... I'll test on 10 but heavy items :)

- on init (empty store) size of bevy_pkv.sled folder is 8.0K
- 10 Doc items added: 40M

    Schema is the following:
    docs: HashMap<id, Doc>
    names: HashMap<id, String>
    tags: HashMap<id, Vec<String>>
    last_saved: id

- `pkv.clear().unwrap();` called: size stays the same 40M
- 10 Doc items added: size is 80M
- `pkv.clear().unwrap();` called: size stays the same 80M

**Comment by johanhelsing** [comment]
Thanks for the detailed testing. Hmm... maybe we should consider switching the default to rocksdb... though It would be really nice to have a well-maintained rust-based alternative backend, not sure if any exist at the moment, though.

**Comment by StaffEngineer** [comment]
Yep, I am also all for the rust-based backend, as long as it works as expected :)
