### ISSUE TITLE
issue with WASM

### ISSUE THREAD

**Issue by jaminhaber** [johanhelsing/bevy_pkv#52]
Hello! I have been running into a crash when running a WASM build. I can confirm it is fixed when i remove the PkvStore initialization

cargo toml
```toml
bevy_embedded_assets = "0.10.0"
bevy_pkv = { git = "https://github.com/johanhelsing/bevy_pkv", branch = "main" }
serde = "1.0.197"
wasm-bindgen = "0.2.91"
```

setup
```rust
app.insert_resource(PkvStore::new("Chillgames", "Sokoban"));
```

error:
```error
6177.115ebb962d0d5d6d.js:1 panicked at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.1/src/backend/wgpu_core.rs:724:18:
Error in Surface::configure: Validation Error

Caused by:
    `Surface` width and height must be within the maximum supported texture size. Requested was (20480, 15360), maximum extent is 16384.
```

**Comment by johanhelsing** [comment]
That seems really strange. Why would bevy_pkv cause errors with wgpu surfaces?

Does it also crash for the examples in this repo?

**Comment by jaminhaber** [comment]
Ah, it seems that removing the library just caused a different error which obfuscated the real error. Not related to this library!
