### ISSUE TITLE
set_string on WASM splits the value on dots

### ISSUE THREAD

**Issue by idanarye** [johanhelsing/bevy_pkv#9]
On WASM, when I use `pkv.set_string` to store a string with a dot (`.`) in it (in the value, not in the key), it splits on the dot and stores an array instead. Needless to say, trying to load that value fails because the type is wrong.

This only happens with `set_string` - using `set` stores the value correctly.

This only happens on WASM - on native `set_string` works properly.

I'm using the version from the latest commit (02c18d117ff7a299ac6e439549aba242b81887bb)

**Comment by johanhelsing** [comment]
Oops. Look like I forgot to json encode the string. Fixed it and added some basic tests.

Thanks for reporting!
